#!/bin/sh -ex

# Check the value of MY_VARIABLE and expose the appropriate port
if [ "$UPS_PORT" == "auto" ]; 
then 
	echo "UPS_PORT is set to auto. Exposing default port $DEFAULT_PORT." 
	export PORT=$DEFAULT_PORT 
else 
	echo "UPS_PORT is set to $UPS_PORT. Exposing custom port $UPS_PORT." 
	export PORT=$UPS_PORT 
fi

if [ -z "$API_PASSWORD" ]
then
	API_PASSWORD=$(dd if=/dev/urandom bs=18 count=1 2>/dev/null | base64)
else
	API_PASSWORD=$(cat /run/secrets/api_password)
fi

if [ -z "$ADMIN_PASSWORD" ]
then
	ADMIN_PASSWORD=$(dd if=/dev/urandom bs=18 count=1 2>/dev/null | base64)
else
	ADMIN_PASSWORD=$(cat /run/secrets/admin_password)
fi

cat >/nut/data/ups.conf <<EOF
[$UPS_NAME]
	desc = "$UPS_DESC"
	driver = $UPS_DRIVER
	port = $UPS_PORT
EOF

cat >/nut/data/upsd.conf <<EOF
LISTEN 0.0.0.0 3493
EOF

cat >/nut/data/upsd.users <<EOF
[$ADMIN_USER]
	password = $ADMIN_PASSWORD
	actions = set
	actions = fsd
	instcmds = all

[$API_USER]
	password = $API_PASSWORD
	upsmon master
EOF

cat >/nut/data/upsmon.conf <<EOF
MONITOR $UPS_NAME@localhost 1 $API_USER $API_PASSWORD master
SHUTDOWNCMD "$SHUTDOWN_CMD"
EOF

chgrp -R nut /nut /dev/bus/usb
chmod -R o-rwx /nut

/usr/sbin/upsdrvctl start
/usr/sbin/upsd
exec /usr/sbin/upsmon -D
